# Generated by Django 5.0.7 on 2025-12-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('likes', models.IntegerField(default=0)),
                ('image', models.URLField(blank=True, default='')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
